### ISSUE TITLE
No license information for src/CircularBuffer.hpp

### ISSUE THREAD

**Issue by shayandoust** [GATB/MindTheGap#12]
Hello,

My name is Shayan Doust[1], a contributor to the Debian-Med team[2]. I have packaged MindTheGap[3], however uploading efforts are unsuccessful as there is no licensing information in src/CircularBuffer.hpp.

Could you please clarify the licensing information within this file? Right now, it only contains a copyright holder but no licensing information. Ideally, include the licensing information in this file (just like the other source files) and generate a new release when you are ready. That way, I can simply integrate the new changes within the package and try for another upload to the Debian repository.

Kind regards,
Shayan Doust

[1]: https://qa.debian.org/developer.php?login=hello%40shayandoust.me
[2]: https://www.debian.org/devel/debian-med/
[3]: https://salsa.debian.org/med-team/mindthegap

**Comment by rchikhi** [comment]
cc @rizkg

**Comment by rizkg** [comment]
Hi, I updated the license info in the file.
@clemaitre , I let you generate the new release when time is right .

**Comment by shayandoust** [comment]
Thanks for the prompt responses! Do let me know when a release is made.

**Comment by clemaitre** [comment]
Thanks @shayandoust for pointing this out and @rizkg for the licence update!
A new release has been made (v2.2.2)
