### ISSUE TITLE
ERROR: Unknown parameter '-contig'

### ISSUE THREAD

**Issue by ashdederich** [GATB/MindTheGap#13]
I am running MindTheGap in 'contig gap-filling' mode and am attempting to run this command: 

'''
MindTheGap fill -nb-cores ${task.cpus} -in 18-01_reads.fq -contig 18-01_assembly.fa -kmer-size 51 -abundance-min 5 -max-nodes 300 -max-length 50000 -out 18-01_gapFilled
'''

However, I keep receiving this error:
'''
ERROR: Unknown parameter '-contig'
ERROR: Unknown parameter '18-01_assembly.fa'
'''
All my reads were gzipped at first to conserve space, and I initially thought that the program could only handle unzipped files, so I gunzipped all of them and re-ran the command, but I am still receiving this same error. I am running this program on an HPC through a container that I downloaded from https://quay.io/repository/biocontainers/mindthegap?tab=tags.

Thank you for your help,
Ashley

**Comment by clemaitre** [comment]
Hi Ashley,

The command line seems fine to me. Which version have you downloaded ? The `-contig` mode is only provided since version 2.1.0.
To get the version, you can run 
```
MindTheGap -version
```

Best,
Claire

**Comment by ashdederich** [comment]
It is up an running now, thank you!
