### ISSUE TITLE
Exception: Hash16: max size for this hash is 2^32, but ask for 33

### ISSUE THREAD

**Issue by pinarkavak** [GATB/MindTheGap#2]
Hello,

I ran MindTheGap on a high coverage (~200x) whole human genome data with a command like this:
./MindTheGap find -in S1_1.fastq.gz,S1_2.fastq.gz,S2_1.fastq.gz,S2_2.fastq.gz,...,S18_1.fastq.gz,S18_2.fastq.gz -ref human_g1k_v37.fasta -nb-cores 72 -max-memory 200000 -out SAMPLE

and got this exception after running for quite a while: 

"EXCEPTION: Hash16: max size for this hash is 2^32, but ask for 33."

What might cause this problem. Did I misuse the computational parameters again? (The machine has 
99 cores and 1TB memory.)

Thank you very much,
pinar

**Comment by rizkg** [comment]
Hi,
Can you try again with a lower max-memory ? For example -max-memory 50000. There might be a bug when asking to use a lot of memory, but anyway it will not speed things up, and the software will run fine with lower amount of ram.
