### ISSUE TITLE
Config Files

### ISSUE THREAD

**Issue by rrfuentes** [GATB/MindTheGap#3]
Hi, I'm running MindTheGap in a cluster but it consumes up the space in my /home directory by writing a lot of trashme_* files. I'm using MindTheGap for 3k rice genomes. Are these files necessary? Can we disable them?

**Comment by rizkg** [comment]
Hi,
Yes these files are necessary.  They will be automatically deleted at the end, but are used for temporary storage during our kmer counting step. 
If possible you should run MindTheGap on a local disk, because these files may indeed be quite large and can cause network congestion if they go to your home dir through the network.

**Comment by rrfuentes** [comment]
Hi,
Is it possible to specify a prefix(path), like that of output file, to indicate a specific location where these temporary files will be written? I need to redirect the writing to other disk to avoid consuming all space in the main cluster node. The previous MindTheGap allows me to run job array without hogging the /home directory.

**Comment by rizkg** [comment]
Hi, indeed the option to choose where the temp files are written is missing in the current release of mindthegap, they are written in the dir where the command is launched.
I just added this option in the latest commit, use  -out-tmp /some_directory   to specify where the temp files will be written. 
If you cannot pull and re-install MindTheGap right now,  your only option is to launch MindTheGap where you want the temp files to be written.

**Comment by rrfuentes** [comment]
Hi, I think some output files were not prefixed yet. I still get some trashme* & trashme*_cfp files in the /home directory after using -out-tmp.
