### ISSUE TITLE
recommended settings for nanopore reads

### ISSUE THREAD

**Issue by colinbrislawn** [GATB/MindTheGap#5]
I'm using `MindTheGap find` to find a 1600 bp insertion inside E coli using oxford nanopore reads. The program runs quickly and reports numerous small insertions and deletions, but the expected longer insertion is not reported.

I know that long and noisy nanopore reads are really different than the short and precise Illumina reads, and I was wondering if you have recommended settings that could help track down this longer insertion.

Thank you so much! 

Here is my current command: `MindTheGap find -in seqs.fastq.gz -ref ecoli.fasta.gz`

**Comment by WesDe** [comment]
Hi, it may be late but the find module produce 3 files : othervariants.vcf that stores deletions and snp, breakpoints files that stores breakpoints from potential insertions and the h5 file that contains your sequencing data in a de bruijn graph format.

Once you get the result from : 
`MindTheGap find -in seqs.fastq.gz -ref ecoli.fasta.gz -out ecoli`
To assemble your insertions, use the command : 
`MindTheGap fill -graph ecoli.h5 -bkpt ecoli.breakpoints -out ecoli`

But you can check in the breakpoints file if a breakpoint near the insertion you search is found.

**Comment by colinbrislawn** [comment]
Thanks for your feedback!
I'll close the issue for now, and let you know if this works for me.
