### ISSUE TITLE
Readme issue

### ISSUE THREAD

**Issue by rchikhi** [GATB/MindTheGap#7]
> -no-[type]: to disable the detection of certain types of variants.

It's not clear that e.g. " -no-snp" is an option, as [type] is never defined

**Comment by rchikhi** [comment]
Also: "maximum number of nodes in contig graph": it is the contig graph constructed for a single insertion, right? If so, please specify it.

**Comment by clemaitre** [comment]
Thank you Rayan for your comments, we have corrected the README.
