### ISSUE TITLE
simple test fails on my machine

### ISSUE THREAD

**Issue by rchikhi** [GATB/MindTheGap#8]
All tests pass except:

n-in-solid-stretch        :  FAILED
n-after-clean-insert      :  FAILED

**Comment by clemaitre** [comment]
Hi Rayan,

this is weird, these tests pass in Jenkins CI, as well as on my machine.
I modified these 2 precise tests in July: are you on the latest commit of master branch ? The two following files should be empty :  test/truths/n_after_gap.fasta and  test/truths/n_in_stretch.fasta

Claire

**Comment by rchikhi** [comment]
I'm on the latest commit of the master branch and the tests fail.
Note that they don't fail on release 2.2.0

**Comment by rchikhi** [comment]
I think the issue is that gatb-core of mindthegap's master branch points to an old commit: 5642ef0

**Comment by clemaitre** [comment]
I do not think gatb-core version is the problem, since gatb-core points to the same commit in release 2.2.0 and in the latest commit of master  = 5642ef0
Does your local copy of MindTheGap points to this same version of gatb-core  ?

**Comment by rchikhi** [comment]
I think I see the problem. I didn't use the INSTALL script to compile the master branch, I had just done `mkdir build && cd build && cmake .. && make -j8`. But the INSTALL script always starts by updating gatb-core.

**Comment by clemaitre** [comment]
Hi Rayan, do all simple tests pass now (once you updated gatb-core) ?

**Comment by rchikhi** [comment]
yes
